services:
  react-ui:
    image: ghcr.io/anwar3006/react-ui:latest
    container_name: react-ui-prod
    ports:
      - "3000:80"
    depends_on:
      - java-cms

  java-cms:
    image: ghcr.io/anwar3006/java-cms:latest
    container_name: java-cms-prod
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_USERNAME: user
      DB_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=mydb"

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgresql_data:
    driver: local
