services:
  react-ui:
    image: ghcr.io/anwar3006/react-ui:latest
    container_name: react-ui-prod
    ports:
      - "3000:80"
    depends_on:
      - java-cms

  java-cms:
    image: ghcr.io/anwar3006/java-cms:latest
    container_name: java-cms-prod
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_USERNAME: dev
      DB_PASSWORD: password
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=dev"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=mydb"

volumes:
  postgresql_data:
    driver: local
